# Generated by Django 2.2.4 on 2019-09-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brf',
            name='founding_year',
            field=models.IntegerField(),
        ),
    ]
