# Generated by Django 2.2.4 on 2019-09-24 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0003_auto_20190918_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brf',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='brfkpi',
            old_name='year',
            new_name='fiscal_year',
        ),
    ]
