# Generated by Django 2.2.4 on 2019-09-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0004_auto_20190924_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brfkpi',
            name='fiscal_year',
            field=models.IntegerField(unique=True),
        ),
    ]
